### ISSUE TITLE
Unable to load files (processNextTick is not a function)

### ISSUE THREAD

**Issue by pecefix** [gingko/client#124]
Today I always get this Loading Error, when trying to open a Gingko file, no matter if the item is stored internally or externally as a "*.gko"-file.

![image](https://user-images.githubusercontent.com/39944697/45107042-9c197880-b138-11e8-88bc-3323552ec80f.png)

**Comment by pecefix** [comment]
Maybe the error has to do with this question, which today I have discovered for the first time when I tried to load my recently used file. After that one I wasn't able to load any file (neither the recently used file nor any other). If you need the information of the debugging tools, please let me know. 
![image](https://user-images.githubusercontent.com/39944697/45109127-d9810480-b13e-11e8-9081-b56dbe0bd89f.png)

**Comment by pecefix** [comment]
Even If I create a new file (BLANK) I cannot reload/open it again, after I saved it. 

This is the debugging tool info.

```
Gingko version 2.2.2    doc.js:199 

Uncaught (in promise) TypeError: processNextTick is not a function
    
at resume (C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:696)
    
at ReadStream.Readable.resume (C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:688)
    
at ReadStream.Readable.on (C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:655)
    
at ReadStream.Readable.pipe (C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:528)
    
at C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\pouchdb\lib\index.js:5689
    
at countDocs (C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\pouchdb\lib\index.js:4934)
    
at C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\pouchdb\lib\index.js:5551
    
at tryCode (C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\pouchdb\lib\index.js:4960)
    
at C:\Users\********\AppData\Local\Programs\gingko-client\resources\app.asar\node_modules\pouchdb\lib\index.js:5007
    
at Array.forEach (<anonymous>)

````
```

**Comment by AdrianoFerrari** [comment]
One other user (so far) has reported this same error. Trying to confirm if it's Windows only, or also present in other platforms.

Thanks Armin for the detailed logs. Looking into this now.

**Comment by AdrianoFerrari** [comment]
I released what I believe is a fix, in version 2.2.3

If you've experienced this error, open Gingko, wait on the "Gingko Home" screen until you get a notification that Gingko has been updated to 2.2.3, then quit and restart.

Let me know, please, if you get an error or not.

**Comment by pecefix** [comment]
2.2.3 installed. 
Yes, I'm able to load files again! Thanks for the fix. 
However, before Gingko load my recently used files, Gingko is asking if I want to recover or discard unsaved changes. This happens only once for each file. After saving the files again, everything seems to be fine.

**Comment by AdrianoFerrari** [comment]
Great! Thanks for letting me know, Armin.

The "recover or discard" is expected... what happens is that it failed loading in previous attempts, and so it didn't close properly, leaving behind a temporary autosave directory.

**Comment by kdambekalns** [comment]
Please re-open this. I have 2.2.3 (even downloaded it again today, to make sure), but I still get this error.

```
Unhandled Error
TypeError: processNextTick is not a function
    at maybeReadMore (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_readable.js:438:5)
    at readableAddChunk (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_readable.js:209:7)
    at DestroyableTransform.Readable.push (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at DestroyableTransform.Transform.push (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at push (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/split2/index.js:52:10)
    at DestroyableTransform.transform [as _transform] (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/split2/index.js:33:5)
    at DestroyableTransform.Transform._read (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at readableAddChunk (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at DestroyableTransform.Readable.push (/Applications/Gingko.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_readable.js:157:10)
```

**Comment by AdrianoFerrari** [comment]
Thanks for letting me know @kdambekalns .
It's possible (judging by the reports so far), that the error was fixed on Win and Linux, but no on macOS.

Will look into it.

**Comment by AdrianoFerrari** [comment]
I'm not able to reproduce this on macOS with 2.2.3
Can you help me out, @kdambekalns ?

If you open Gingko, create a new Blank document, and then do "Help > Open Debugging Tools".
Let me know what it says both for "Gingko version" at top, and what output you get on typing  `process.versions` there?

Just want to know if it it's an issue with 2.2.3, or an issue with old code hanging around (somehow) from 2.2.2 even after re-download/re-install.

**Comment by kdambekalns** [comment]
`Gingko version 2.2.3` and
```
ares:"1.10.1-DEV"
chrome:"61.0.3163.100"
electron:"2.0.8"
http_parser:"2.7.0"
modules:"57"
nghttp2:"1.25.0"
node:"8.9.3"
openssl:"1.0.2n"
uv:"1.15.0"
v8:"6.1.534.41"
zlib:"1.2.11"
```

**Comment by kdambekalns** [comment]
Oh, and: saving and reopening a new document works…

**Comment by kdambekalns** [comment]
Ir works! 👏

(Only thing is, I have never before seen a licensing dialog when starting the app.)

**Comment by AdrianoFerrari** [comment]
Great, thanks for letting me know.
I made that release public, so it should update automatically to 2.2.4 for everyone.

PS: Regarding licensing dialog, if you mean a window describing the trial period, and how many days left, it's something that isn't meant to appear every time you open, but only on select number of days left (25, 20, 15, etc). Note that this is number of days of *usage*, so it should give plenty of time to try. If you have more questions, get in touch, or open an issue.

**Comment by kdambekalns** [comment]
Great, thanks for fixing so quickly! 🍺
