### ISSUE TITLE
Export as Text (Windows) : Entire document appears on one line

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#42]
Seems to be an issue with line-endings, because the same files open correctly on Linux.

**Comment by AdrianoFerrari** [comment]
I'm adding a `"\n\n"` here:
https://github.com/gingko/client/blob/master/src/elm/Coders.elm#L308

This doesn't result in newlines on Windows. Likely I will have to replace `\n` with `\r\n` somewhere.

**Comment by AdrianoFerrari** [comment]
Seems that this might only be an issue when opened in Notepad. More "modern" text editors, like "Wordpad" can open files with both endings.

Still, might be worth adding the line endings that Windows expects, to prevent confusion.

**Comment by ipalindromi** [comment]
My guess is you're right about needing `\r\n`. I'll look into this!

**Comment by ipalindromi** [comment]
So the change you suggested did get us partway there 
![image](https://user-images.githubusercontent.com/1351129/38054706-c433080c-32a5-11e8-865b-afc6eb3c4ab0.png)

That adds a carriage return after each card's content, but the content itself still outputs with `\n`. I assume this isn't expected behavior. It's not what I would expect, anyway. 

I haven't been able to find where that behavior is explicitly set, yet, and it makes me think it might be intrinsic to the environment or something like that? Or I'm just missing it. I figured I would ask if you have any ideas on why that would be before looking into alternate options, @AdrianoFerrari .

**Comment by AdrianoFerrari** [comment]
Ah yes. Oops!
It's not just between card line endings that need to be replaced.

Probably something like:
```js
data = process.platform === "win32" ? data.replace(/\n/g, "\r\n") : data;
```
around here:
https://github.com/gingko/client/blob/master/src/shared/main.js#L625

Would do the trick. Haven't tested it, though.

**Comment by ipalindromi** [comment]
Hey Adriano! I pushed a commit for this just after you did! It handles the same thing slightly differently. Handling the case of data being a non-string may or may not be a concern. I figured I'd send it along for your input on that.

https://github.com/ipalindromi/client/commit/b4fa4a4857ea2b1a5a9c124d0e02261b9816d279

**Comment by AdrianoFerrari** [comment]
Yes, your solution is better and safer... I think I'm getting too used to Elm and it's safety, that I'm forgetting to check for error cases in JS!

Make a PR and I'll replace it with mine.

PS: Sorry for going ahead with the fix... I'm still getting used to open source :)

**Comment by ipalindromi** [comment]
No worries, this is new to me too! I'll rebase and put in a PR!

**Comment by AdrianoFerrari** [comment]
Woohoo!
Thanks for the help :+1:
